# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-04 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20190502_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='endpoint_url',
            field=models.CharField(blank=True, help_text='External URL for handling form submissions rather than the CMS', max_length=200, null=True, verbose_name='Endpoint url'),
        ),
    ]
